name: fix-eslint

# 当push时触发
on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # 此处是为了获取 github token，用于修复eslint后 push 代码
      # with:
      #   token: ${{ secrets.ACCESS_TOKEN }}



    # 使用 nodejs v10.15.3 的版本
    - name: Use Node.js v10.15.3
      uses: actions/setup-node@v3
      with:
        node-version: v10.15.3

    # 安装依赖
    - name: Install
      run: npm i --registry=http://registry.npmmirror.com

    # fix
    - name: fix
      run: npm run lint:fix

    # TODO: 修复代码后 push 到远程仓库，需要配置上面的 github token
    - name: Push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "fix: eslint"
        git push
